# Generated by Django 4.0.4 on 2022-08-18 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_likes', models.CharField(blank=True, max_length=50, null=True)),
                ('adres', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('karta', 'Karta'), ('gotowka', 'Gotowka'), ('zaplacone', 'Zaplacone')], default='zaplacone', max_length=10)),
                ('amount', models.CharField(max_length=5)),
                ('phone', models.CharField(default='+48', max_length=13)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(choices=[('uber', 'Uber'), ('rest', 'Rest'), ('glovo', 'Glovo'), ('tel', 'Tel')], default='glovo', max_length=5)),
                ('status', models.CharField(choices=[('oczekujacy', 'Oczekujacy'), ('w trakcie', 'W trakcie'), ('zakonczony', 'Zakonczony')], default='oczekujacy', max_length=10)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
