# Generated by Django 4.0.4 on 2022-08-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='oczekujace',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='trasa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='zakonczone',
            field=models.BooleanField(default=False),
        ),
    ]
