# Generated by Django 4.0.4 on 2022-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_status_post_oczekujace_post_trasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nr_domu',
            field=models.CharField(default=22, max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
