# Generated by Django 4.0.4 on 2022-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_nr_domu_alter_post_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nr_domu',
            field=models.CharField(max_length=4),
        ),
    ]
