# Generated by Django 4.0.4 on 2022-08-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_nr_domu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='komentarz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='amount',
            new_name='kwota',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='platform',
            new_name='platforma',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='phone',
            new_name='telefon',
        ),
    ]
