# Generated by Django 4.0.4 on 2022-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_restaurator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restauracja',
            field=models.CharField(choices=[('joe', 'Joe'), ('czeska', 'Czeska'), ('mexicana', 'Mexicana')], default='Joe', max_length=20),
        ),
    ]
