# Generated by Django 4.0.4 on 2022-09-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_restauracja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restauracja',
            field=models.CharField(choices=[('Joe Gonzalez', 'joe'), ('Czeska Gospoda', 'czeska'), ('Mexicana', 'mexicana')], default='Joe', max_length=20),
        ),
    ]
