# Generated by Django 4.0.4 on 2022-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_restauracja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restauracja',
            field=models.CharField(choices=[('Joe Gonzalez', 'Joe Gonzalez'), ('Czeska Gospoda', 'Czeska Gospoda'), ('Mexicana', 'Mexicana')], default='Joe', max_length=50),
        ),
    ]
