# Generated by Django 4.0.4 on 2022-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_restauracja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_restaurator',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stanowisko',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Restaurator', 'Restaurator')], default='Driver', max_length=50),
        ),
    ]
